baseurl = "/"
title = "ack.zone"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "color"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "ackzone"

[params]
    author = "Jay Wallace"
    info = "An engineer who occasionally writes"
    description = "professional rants"
    keywords = "blog,developer,personal"

    footercontent = "This is water 🌊"

    hidecredits = true
    hidecopyright = true
    avatarurl = "img/avatar.jpg"
    favicon_32 = "/img/favicon-32x32.png"
    favicon_16 = "/img/favicon-16x16.png"

    rtl = false

    math = true
    custom_css = ["css/custom.css"]

# Social links
[[params.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    weight = 1
    url = "https://github.com/mootpt/"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter fa-2x"
    weight = 2
    url = "https://twitter.com/mootpt/"
[[params.social]]
    name = "Linkedin"
    icon = "fab fa-linkedin fa-2x"
    weight = 3
    url = "https://www.linkedin.com/in/cantc/"

# Menu links
[[menu.main]]
    name = "Blog"
    weight = 1
    url  = "/posts/"
[[menu.main]]
    name = "About"
    weight = 2
    url = "/about/"

